services:
  python_app:
    build:
      context: ./python_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
      - DB_NAME=AxShop
      - DB_PORT=5435

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: AxShop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      PGPORT: 5435
    volumes:
      - db-data:/mnt/docker
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5435:5435"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db

  spring:
    build:
      context: ./Spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5435/AxShop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
      - frontend
    volumes:
      - ./Spring:/app
      - ~/.m2:/root/.m2  # Кэш Maven для ускорения сборки

volumes:
  db-data:
